# Generated by Django 3.1.2 on 2020-11-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
