# Generated by Django 3.1.2 on 2020-11-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
