# Generated by Django 3.1.2 on 2020-11-03 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('chosen', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'image'), ('text', 'text'), ('emoji', 'emoji'), ('sticker', 'sticker'), ('unsplash', 'unsplash'), ('gif', 'gif'), ('yesNo', 'yesNo'), ('check', 'check'), ('radio', 'radio'), ('timer', 'timer'), ('range', 'range'), ('button', 'button')], max_length=500)),
                ('title', models.CharField(blank=True, default='default text for widget', max_length=500, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('src', models.TextField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('choiceSum', models.IntegerField(blank=True, default=0, null=True)),
                ('clicks', models.IntegerField(blank=True, default=0, null=True)),
                ('rangeTimes', models.FloatField(blank=True, default=0, null=True)),
                ('rangeCount', models.IntegerField(blank=True, default=0, null=True)),
                ('yesTimes', models.IntegerField(blank=True, default=0, null=True)),
                ('noTimes', models.IntegerField(blank=True, default=0, null=True)),
                ('yesNoCount', models.IntegerField(blank=True, default=0, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('seconds', models.IntegerField(blank=True, null=True)),
                ('transX', models.CharField(default='-50%', max_length=500)),
                ('transY', models.CharField(default='-50%', max_length=500)),
                ('top', models.CharField(default='50%', max_length=500)),
                ('left', models.CharField(default='50%', max_length=500)),
                ('width', models.CharField(default='220px', max_length=500)),
                ('height', models.CharField(default='auto', max_length=500)),
                ('rotation', models.CharField(default='0deg', max_length=500)),
                ('background', models.CharField(blank=True, default='white', max_length=500, null=True)),
                ('color', models.CharField(blank=True, default='#333', max_length=500, null=True)),
                ('choices', models.ManyToManyField(blank=True, null=True, to='clone_app.choices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('background', models.CharField(default='white', max_length=500)),
                ('components', models.ManyToManyField(blank=True, null=True, to='clone_app.components')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
