# Generated by Django 3.1.2 on 2020-11-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='type',
            field=models.CharField(choices=[('image', 'image'), ('text', 'text'), ('emoji', 'emoji'), ('sticker', 'sticker'), ('unsplash', 'unsplash'), ('gif', 'gif'), ('yesNo', 'yesNo'), ('check', 'check'), ('radio', 'radio'), ('timer', 'timer'), ('range', 'range'), ('button', 'button')], max_length=500),
        ),
    ]
