# Generated by Django 3.1.2 on 2020-11-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0002_auto_20201101_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='data_src',
        ),
        migrations.AlterField(
            model_name='components',
            name='height',
            field=models.CharField(default='auto', max_length=500),
        ),
        migrations.AlterField(
            model_name='components',
            name='title',
            field=models.CharField(blank=True, default='default text for widget', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='width',
            field=models.CharField(default='220px', max_length=500),
        ),
    ]
