# Generated by Django 3.1.2 on 2020-11-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0003_storiesset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='storiesset',
            name='product',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
