# Generated by Django 3.1.2 on 2020-11-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0003_auto_20201101_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='rotation',
            field=models.CharField(default='0deg', max_length=500),
        ),
    ]
