# Generated by Django 3.1.2 on 2020-11-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0004_storiesset_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='storiesset',
            name='price',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
    ]
