# Generated by Django 3.1.2 on 2020-11-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0005_auto_20201102_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='choiceSum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='clicks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='noTimes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='rangeCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='rangeTimes',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='yesNoCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='yesTimes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
