# Generated by Django 3.1.2 on 2020-11-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0006_auto_20201102_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='left',
            field=models.CharField(default='50%', max_length=500),
        ),
        migrations.AddField(
            model_name='components',
            name='top',
            field=models.CharField(default='50%', max_length=500),
        ),
    ]
