# Generated by Django 3.1.2 on 2020-10-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0006_auto_20201023_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
