# Generated by Django 3.1.2 on 2020-10-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0007_story_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='answers',
            field=models.IntegerField(default=0),
        ),
    ]
