# Generated by Django 3.1.2 on 2020-11-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0008_storiesset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='storiesset',
            name='handle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
