# Generated by Django 3.1.2 on 2020-10-26 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clone_app', '0008_story_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('chosen', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='story',
            name='story_images',
        ),
        migrations.AlterField(
            model_name='story',
            name='story',
            field=models.TextField(default='\n        <div class="innerStoryCard" style="overflow:hidden;"></div>\n    '),
        ),
        migrations.CreateModel(
            name='components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'image'), ('text', 'text'), ('emoji', 'emoji'), ('yesNo', 'yesNo'), ('check', 'check'), ('radio', 'radio'), ('timer', 'timer'), ('range', 'range')], max_length=500)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('html', models.TextField(blank=True, null=True)),
                ('range', models.IntegerField(blank=True, null=True)),
                ('choices', models.ManyToManyField(to='clone_app.choices')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='components',
            field=models.ManyToManyField(to='clone_app.components'),
        ),
    ]
