# Generated by Django 3.1.2 on 2020-11-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0009_storiesset_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='fontFamily',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='fontSize',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='target',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='textAlign',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='storyType',
            field=models.CharField(choices=[('design', 'design'), ('checkout', 'checkout')], default='design', max_length=500),
        ),
    ]
