# Generated by Django 3.1.2 on 2020-10-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0009_auto_20201026_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story',
        ),
        migrations.AddField(
            model_name='components',
            name='height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='components',
            name='transX',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='components',
            name='transY',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='components',
            name='width',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='background',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
