# Generated by Django 3.1.2 on 2020-10-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0010_auto_20201026_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='choices',
            field=models.ManyToManyField(blank=True, null=True, to='clone_app.choices'),
        ),
        migrations.AlterField(
            model_name='story',
            name='components',
            field=models.ManyToManyField(blank=True, null=True, to='clone_app.components'),
        ),
    ]
