# Generated by Django 3.1.2 on 2020-11-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0010_auto_20201107_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='fontFamily',
            field=models.CharField(blank=True, default='Helvetica', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='textAlign',
            field=models.CharField(blank=True, default='center', max_length=500, null=True),
        ),
    ]
