# Generated by Django 3.1.2 on 2020-10-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0011_auto_20201026_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='components',
            old_name='range',
            new_name='noCount',
        ),
        migrations.AddField(
            model_name='components',
            name='noTimes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='rangeCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='rangeTimes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='yesCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='yesTimes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='transX',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='components',
            name='transY',
            field=models.FloatField(default=0),
        ),
    ]
