# Generated by Django 3.1.2 on 2020-11-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0011_auto_20201107_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='components',
            name='seconds',
        ),
        migrations.AddField(
            model_name='components',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
