# Generated by Django 3.1.2 on 2020-10-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0012_auto_20201026_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='transX',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='components',
            name='transY',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
