# Generated by Django 3.1.2 on 2021-04-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0013_auto_20201117_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='choices',
            field=models.ManyToManyField(blank=True, to='clone_app.choices'),
        ),
        migrations.AlterField(
            model_name='story',
            name='components',
            field=models.ManyToManyField(blank=True, to='clone_app.components'),
        ),
    ]
