# Generated by Django 3.1.2 on 2020-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0013_auto_20201027_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='components',
            name='transX',
            field=models.CharField(default='-50%', max_length=500),
        ),
        migrations.AlterField(
            model_name='components',
            name='transY',
            field=models.CharField(default='-50%', max_length=500),
        ),
    ]
