# Generated by Django 3.1.2 on 2020-10-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0014_auto_20201027_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='background',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='components',
            name='color',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
