# Generated by Django 3.1.2 on 2021-04-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0014_auto_20210407_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='components',
            name='type',
            field=models.CharField(choices=[('image', 'image'), ('text', 'text'), ('emoji', 'emoji'), ('sticker', 'sticker'), ('unsplash', 'unsplash'), ('gif', 'gif'), ('yesNo', 'yesNo'), ('check', 'check'), ('radio', 'radio'), ('timer', 'timer'), ('range', 'range'), ('button', 'button'), ('checkout', 'checkout'), ('dataCollector', 'dataCollector')], max_length=500),
        ),
        migrations.AddField(
            model_name='components',
            name='entries',
            field=models.ManyToManyField(blank=True, to='clone_app.Entry'),
        ),
    ]
