# Generated by Django 3.1.2 on 2020-10-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_app', '0015_auto_20201027_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='href',
            field=models.URLField(blank=True, null=True),
        ),
    ]
